src/Entity/ItemsInInvoice.php
<?php

namespace App\Entity;

use App\Repository\ItemsInInvoiceRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ItemsInInvoiceRepository::class)]
class ItemsInInvoice
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'itemsInInvoices')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Products $Product_Id = null;

    #[ORM\ManyToOne(inversedBy: 'itemsInInvoices')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Invoice $Invoice_id = null;

    #[ORM\Column]
    #[Assert\Range(
        min: 1,
        minMessage: 'Количество должно быть больше 0'
    )]
    private ?int $count = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProductId(): ?Products
    {
        return $this->Product_Id;
    }

    public function setProductId(?Products $Product_Id): static
    {
        $this->Product_Id = $Product_Id;

        return $this;
    }

    public function getInvoiceId(): ?Invoice
    {
        return $this->Invoice_id;
    }

    public function setInvoiceId(?Invoice $Invoice_id): static
    {
        $this->Invoice_id = $Invoice_id;

        return $this;
    }

    public function getCount(): ?int
    {
        return $this->count;
    }

    public function setCount(int $count): static
    {
        $this->count = $count;

        return $this;
    }
}

src/Entity/Products.php
<?php

namespace App\Entity;

use App\Repository\ProductsRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ProductsRepository::class)]
class Products
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    #[Assert\Range(
        min: 1,
        minMessage: 'Количество должно быть больше 0'
    )]
    private ?int $count = null;

    #[ORM\Column(length: 30)]
    private ?string $units = null;

    #[ORM\Column]
    #[Assert\Range(
        min: 1,
        minMessage: 'Цена должна быть больше 0'
    )]
    private ?float $price = null;

    #[ORM\Column]
    private ?bool $IsDeleted = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getCount(): ?int
    {
        return $this->count;
    }

    public function setCount(int $count): static
    {
        $this->count = $count;

        return $this;
    }

    public function getUnits(): ?string
    {
        return $this->units;
    }

    public function setUnits(string $units): static
    {
        $this->units = $units;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): static
    {
        $this->price = $price;

        return $this;
    }

    public function isIsDeleted(): ?bool
    {
        return $this->IsDeleted;
    }

    public function setIsDeleted(bool $IsDeleted): static
    {
        $this->IsDeleted = $IsDeleted;

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;


use App\Entity\Invoice;
use App\Entity\ItemsInInvoice;
use App\Entity\Products;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{

    #[Route("/", name: "Products")]
    function ProductsPage(ManagerRegistry $doctrine)
    {
        $items = $doctrine->getRepository(Products::class)->findAll();
        return $this->render('Main/Products.html.twig', ['items' => $items]);
    }

    #[Route("/invoice", name: "Invoice")]
    function InvoicePage(ManagerRegistry $doctrine)
    {
        $items = $doctrine->getRepository(Invoice::class)->findAll();
        return $this->render('Main/Invoice.html.twig', ['items' => $items]);
    }

    #[Route("/items_in_invoice", name: "Items_in_invoice")]
    function ItemsInInvoicePage(ManagerRegistry $doctrine)
    {
        $items = $doctrine->getRepository(ItemsInInvoice::class)->findAll();

        return $this->render('Main/ProductsInInvoice.html.twig', ['items' => $items]);
    }
}

templates/Main/Invoice.html.twig
{% extends 'base.html.twig' %}
{% block add_button %}
    <a href="{{ path('app_add_invoice')}}" style="text-decoration: none; color: #FFFFFF"><img src="{{ asset('icons/icons8-plus.svg') }}"></a>
{% endblock %}
{% block main %}
    <h1 style="text-align: center">Накладные</h1>
    <div class = 'grid'>
        <table>
            <tr>
                <th>id</th>
                <th>Номер накладной</th>
                <th>Тип</th>
            </tr>
            {% if items != null %}
                {% for item in items %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.number }}</td>
                        <td>{{ item.type }}</td>
                    </tr>
                {% endfor %}
            {% endif %}
        </table>
    </div>
{% endblock %}

templates/Main/Products.html.twig
{% extends 'base.html.twig' %}
{% block add_button %}
    <a href="{{ path('app_add_item')}}" style="text-decoration: none; color: #FFFFFF"><img src="{{ asset('icons/icons8-plus.svg') }}"></a>
{% endblock %}
{% block main %}
    <h1 style="text-align: center">Товары</h1>
    <div class = 'grid'>
        <table>
            <tr>
                <th>id</th>
                <th>Наименование товара</th>
                <th>Цена за единицу</th>
                <th> </th>
                <th> </th>
            </tr>
            {% if items != null %}
                {% for item in items %}
                    {% if item.isDeleted == false %}
                        <tr>
                            <td>{{ item.id }}</td>
                            <td>{{ item.name }}</td>
                            <td>{{ item.price }}</td>
                            <td style="width: 15px">
                                <a href="{{ path('app_delete_item', {'item_id':item.id}) }}">
                                    <img src = "{{ asset('icons/free-icon-font-cross-3917189.svg') }}" width="20px" height="30px">
                                </a>
                            </td>
                            <td style="width: 15px">
                                <a href="{{ path('app_edit_item', {"item_id": item.id}) }}">
                                    <img src = "{{ asset('icons/free-icon-font-pencil-3917376.svg') }}" width="20px" height="20px">
                                </a>
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </table>
    </div>
{% endblock %}

templates/Main/ProductsInInvoice.html.twig
{% extends 'base.html.twig' %}
{% block add_button %}
    <a href="{{ path('app_add_ItemsInInvoice')}}" style="text-decoration: none; color: #FFFFFF"><img src="{{ asset('icons/icons8-plus.svg') }}"></a>
{% endblock %}
{% block main %}
    <h1 style="text-align: center">Приход/Расход</h1>
    <div class = 'grid'>
        <table>
            <tr>
                <th>id</th>
                <th>Наименование товара</th>
                <th>Номер накладной</th>
                <th>Количество</th>
            </tr>
            {% if items != null %}
                {% for item in items %}
                    <tr>
                        <td>{{ item.id }}</td>
                        <td>{{ item.productId.name }}</td>
                        <td>{{ item.invoiceId.number }}</td>
                        <td>{{ item.count}}</td>
                    </tr>
                {% endfor %}
            {% endif %}
        </table>
    </div>
{% endblock %}

templates/Main/index.html.twig
{% extends 'base.html.twig' %}
{% block main %}
    <h1 style="text-align: center">Товары</h1>
    <div class = 'grid'>
        <table>
            <tr>
                <th>id</th>
                <th>Наименование товара</th>
                <th>Количество</th>
                <th>Единицы измерения</th>
                <th>Цена за единицу</th>
                <th> </th>
                <th> </th>
            </tr>
            {% if items != null %}
                {% for item in items %}
                    {% if item.isDeleted == false %}
                        <tr>
                            <td>{{ item.id }}</td>
                            <td>{{ item.name }}</td>
                            <td>{{ item.count }}</td>
                            <td>{{ item.units }}</td>
                            <td>{{ item.price }}</td>
                            <td style="width: 15px">
                                <a href="{{ path('app_delete_item', {'item_id':item.id}) }}">
                                    <img src = "{{ asset('icons/free-icon-font-cross-3917189.svg') }}" width="20px" height="30px">
                                </a>
                            </td>
                            <td style="width: 15px">
                                <a href="{{ path('app_edit_item', {"item_id": item.id}) }}">
                                    <img src = "{{ asset('icons/free-icon-font-pencil-3917376.svg') }}" width="20px" height="20px">
                                </a>
                            </td>
                        </tr>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </table>
    </div>
{% endblock %}